### ISSUE TITLE
Allow hiding logs when taking a snapshot

### ISSUE THREAD

**Issue by lworkman** [happo/happo-cypress#111]
I'm working on cleaning up our logging during Cypress tests, and can't find a way to disable the log from calling `cy.task('happoRegisterSnapshot')`. It's happening when I take a screenshot via `.happoScreenshot`, and looking at the source code it appears there's no way to pass down a `log: false` value: 

https://github.com/happo/happo-cypress/blob/4c67374bbd371de02577f842290e9c680fa98e85/index.js#L83C14-L90

`cy.task` [does allow hiding of logs](https://docs.cypress.io/api/commands/task#Arguments), so there's nothing stopping the log from respecting a `log: false` argument.  Ideally `happoScreenshot` would just pass down its own log value.

Is there anyway this can be added?

**Comment by trotzig** [comment]
Thanks for the report @lworkman! I'm working on a fix for this right away.

**Comment by trotzig** [comment]
A fix for this was released in version 4.2.0. 🚀

https://github.com/happo/happo-cypress/releases/tag/v4.2.0

**Comment by trotzig** [comment]
Documentation is also updated, here: https://docs.happo.io/docs/cypress#passing-along-options

**Comment by lworkman** [comment]
Thanks for the quick turnaround @trotzig!
