### ISSUE TITLE
happoScreenshot doesn't exist on cy

### ISSUE THREAD

**Issue by ar5had** [happo/happo-cypress#17]
In order to stop eslint/typescript from complaining `happoScreenshot` doesn't exist on `cy`, do the following things -

1. Follow https://docs.cypress.io/guides/tooling/typescript-support.html#Install-TypeScript
2. Create `types/happo/index.d.ts` in your cypress folder with the below content -
``` javascript
// https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require
import Cypress = require('cypress');

declare global {
    namespace Cypress {
        interface Chainable {
            happoScreenshot: (options?: any, otherOptions?: any) => void;
        }
    }
}
```
3. Add `"files": ["types/happo/index.d.ts"]` line to your tsconfig.json file in cypress folder.

Now, eslint won't complain about the `happoScreenshot` method on `cy` object.

**Comment by trotzig** [comment]
Thanks @ar5had! Is this something we could provide in this library? We’re not using typescript ourselves but it seems like we should be able to send along the right types with the library.

**Comment by ar5had** [comment]
@trotzig I haven't published types for any library myself, but something like this can be done https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41222/files

or maybe just adding the `index.d.ts` and `tsconfig.json` file in the root of `happo-cypress` repo will work as well.
