### ISSUE TITLE
Customize cypress tests folder

### ISSUE THREAD

**Issue by mat-sf** [happo/happo-cypress#46]
Package: happo-cypress
Version: 1.9.2

By default `happo-cypress` looks for tests in `cypress/integration` folder, but my tests are in `cypress/with-mock` folder, and I would like to be able to customize that path, currently running `npx happo-cypress --allow-failures -- npx cypress run` returns:
```
[HAPPO] Listening on port X
Can't run because no spec files were found.

We searched for any files inside of this folder:

{projectPath}/cypress/integration
```

`npx happo-cypress --help` doesn't return any options as well

**Comment by trotzig** [comment]
Is there a flag you can pass to the `npx cypress run` command that changes the default location to look for spec files? The `happo-cypress` command is mostly a wrapper, you should be able to invoke any arbitrary command after it. How are you invoking a cypress run normally (without happo-cypress)?

**Comment by mat-sf** [comment]
You're right, `npx cypress run --config integrationFolder=cypress/mock-api`, closing then, thank you!

**Comment by trotzig** [comment]
Glad you found a solution!
