### ISSUE TITLE
`npx happo-cypress` returns an error: Cannot find module 'happo.io/build/makeRequest'

### ISSUE THREAD

**Issue by snickell** [happo/happo-cypress#47]
On a few systems I've tried (one OSX, two linux, all recent-ish but not super recent node versions) `npx happo-cypress` appears to no longer work. It could perhaps be a stale package somewhere in my stack, but reporting in case others can reproduce this.

When I run `npx happo-cypress` on all three systems I get:
```
➜  deploy git:(master) ✗ npx happo-cypress
npx: installed 74 in 7.45s
Cannot find module 'happo.io/build/makeRequest'
Require stack:
- /Users/seth/.npm/_npx/22990/lib/node_modules/happo-cypress/bin/happo-cypress.js
```

**Comment by snickell** [comment]
There it is :-) Old version of happo.io installed globally, not compatible with happo-cypress latest.

**Comment by trotzig** [comment]
Glad you figured it out!
