### ISSUE TITLE
Cypress plugin not able to fetch data

### ISSUE THREAD

**Issue by filiphric** [happo/happo-cypress#5]
Hello there!

I’m trying out integrating Happo with Cypress. During my headless run, it seems that happo is not able to download all the needed assets. These are not external, they are all on the same domain as the app I’m trying to test.

<img width="620" alt="Screenshot 2020-05-28 at 09 56 39" src="https://user-images.githubusercontent.com/23213553/83115003-066f0b00-a0ca-11ea-8c6b-8e89c6bd9f05.png">

This results in a page rendered without images (svg format)
<img width="374" alt="Screenshot 2020-05-28 at 09 58 12" src="https://user-images.githubusercontent.com/23213553/83115099-2d2d4180-a0ca-11ea-8dc8-cbe0303973e0.png">

desired appearance:
<img width="375" alt="Screenshot 2020-05-28 at 10 02 04" src="https://user-images.githubusercontent.com/23213553/83115197-5221b480-a0ca-11ea-9383-af4a57e686ba.png">

How can I enable fetching these assets?

**Comment by trotzig** [comment]
Hi @filiphric! Quick response, I’ll have a closer look at this later today —

Are these assets showing up when you run Cypress without happo?

**Comment by filiphric** [comment]
Hello Henric, yes, the complete screenshot is actually from Cypress, I just didn’t include the whole view 🙂

**Comment by trotzig** [comment]
Okay, got it! Second question is if you’re defining `baseUrl` in your cypress config?

**Comment by filiphric** [comment]
oh. this might actually cause something. I’m visiting `app.sli.do` but the baseUrl is set to `sli.do` could this be the problem?

**Comment by trotzig** [comment]
That is likely a problem, although we should be able to handle that case as well.

**Comment by trotzig** [comment]
I found a fix that I'm releasing in a sec. Hold on.

**Comment by trotzig** [comment]
Released in [v1.0.1](https://github.com/happo/happo-cypress/releases/tag/v1.0.1). 

@filiphric Let me know if that release doesn't help resolve your issue!
