### ISSUE TITLE
Review types for happo-cypress

### ISSUE THREAD

**Issue by alexanderpolyankin** [happo/happo-cypress#63]
Hey! I've encountered similar issues as in https://github.com/happo/happo-cypress/issues/17. With typescript, you have to add type definitions manually to call `happo-cypress` methods. I'd like to publish these types to DefinitelyTyped. Here are the types: https://github.com/alexanderpolyankin/DefinitelyTyped/tree/master/types/happo-cypress. Can you please review them? Are you ok with publishing these types?  

The reason why I want to publish these types as `@types` is because [typeRoots](https://www.typescriptlang.org/tsconfig#typeRoots) are set to `@types` by default, so it's the only option that won't require consumers to change their tsconfig settings.

**Comment by trotzig** [comment]
Hi @alexanderpolyankin! Sorry - I totally missed this. I've reviewed the types and they look good 👍. You can go ahead and publish.

**Comment by alexanderpolyankin** [comment]
Thanks a lot!
