### ISSUE TITLE
Types for happo-cyrpress installing an old version of Cypress

### ISSUE THREAD

**Issue by Belco90** [happo/happo-cypress#93]
Hi there!

I've been using Happo for a while for [this project](https://octoclairvoyant.vercel.app/). Really happy with it, great Visual Testing tool!

I just realized I was getting two different Cypress versions installed in my system: v9 (the one I use) and v6. It turns out the package `types/happo-cypress` is setting `cypress@6` as a dependency, so I guess this isn't correctly indicated?

![CleanShot 2022-04-09 at 15 06 21](https://user-images.githubusercontent.com/2677072/162575384-40a4c674-4f95-434a-9821-88450992bdb9.png)

I know the types are managed directly within DefinitelyTyped, but I wanted to flag the issue here. I'll try to create a PR in DefinitelyTyped to fix this, I guess I can entirely remove `cypress` as dependency of those types, right?

**Comment by Belco90** [comment]
It seems it's not that straightforward! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57460

**Comment by Belco90** [comment]
Updated here 🤞  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59790

**Comment by Belco90** [comment]
Solved! `@types/happo-cypress` v3 was published: https://www.npmjs.com/package/@types/happo-cypress

**Comment by trotzig** [comment]
@Belco90 Thanks a bunch for pushing this through! This whole issue managed to slip through the cracks -- I salute you for pushing it through by yourself! 🎉
