### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [happo/happo-cypress#94]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by trotzig** [comment]
Thanks for the heads up! We'll look into it.

**Comment by trotzig** [comment]
Thanks again @admah -- our docs have been updated based on the migration guide. We didn't have to do any code changes in this library, all you have to do is to move some config around. 🎉

**Comment by admah** [comment]
@trotzig I'm really happy to hear that's all it was! If I can help in any other way, feel free to reach out!
